import turtle
from random import *
from math import *
import tkinter
turtle.colormode(255)
turtle.hideturtle()
robot = turtle.Turtle()
#robot.hideturtle()
screen_dimension = turtle.screensize()
x_origin = screen_dimension[0]//2
y_origin = screen_dimension[1]//2
robot.penup()
robot.goto((-1*x_origin),-1*y_origin)
n1=80
n2=160
n3=40
x_origin = robot.xcor()
y_origin = robot.ycor()
EAST,NORTH,WEST,SOUTH = 0,90,180,270
x_axis = 600
y_axis = 800
step = 50
robot.setheading(EAST)
robot.color('blue')
robot.pendown()
robot.forward(x_axis)
robot.shape('arrow')
robot.stamp()
x_axis_x_coord = robot.xcor()
x_axis_y_coord = robot.ycor()
robot.penup()
robot.goto(x_origin,y_origin)
robot.color('red')
robot.setheading(NORTH)
robot.pendown()
robot.forward(y_axis)
y_axis_x_coord = robot.xcor()
y_axis_y_coord = robot.ycor()
robot.shape('arrow')
robot.stamp()
robot.penup()
robot.goto(x_origin,y_origin)
robot.setheading(EAST)
robot.forward(step)
r = randint(0,255)
g = randint(0,255)
b = randint(0,255)
robot.setheading(NORTH)
robot.pendown()
robot.fillcolor((r,g,b))
robot.begin_fill()
robot.forward(n1)
robot.right(90) # robot.setheading(EAST)
robot.forward(step)
robot.right(90)
robot.forward(n1)
robot.right(90)
robot.forward(step)
#robot.right(90)
robot.end_fill()
robot.penup()
robot.setheading(EAST)
robot.forward((step+step))
robot.pendown()
robot.setheading(NORTH)
robot.pendown()
r = randint(0,255)
g = randint(0,255)
b = randint(0,255)
robot.fillcolor((r,g,b))
robot.begin_fill()
robot.forward(n2)
robot.right(90)
robot.forward(step)
robot.right(90) # or robot.setheading(SOUTH)
robot.forward(n2)
robot.setheading(WEST)
robot.forward(step)
robot.end_fill()
robot.penup()
robot.setheading(EAST)
robot.forward((step+step))
robot.setheading(NORTH)
robot.pendown()
r = randint(0,255)
g = randint(0,255)
b = randint(0,255)
robot.fillcolor((r,g,b))
robot.begin_fill()
robot.forward(n3)
robot.setheading(EAST)
robot.forward(step)
robot.setheading(SOUTH)
robot.forward(n3)
robot.setheading(WEST)
robot.forward(step)
robot.end_fill()
tkinter.mainloop()
